added tooltips to all node edit fields
gravitl/netmaker-ui pull request #165
Opened 2022-07-01 19:12 UTC by FatherWolf

added tooltip to every field in node edit to describe what it is used for

2022-07-01 19:13 UTC, FatherWolf commented
![Screenshot from 2022-07-01 15-13-09](https://user-images.githubusercontent.com/93891529/176956288-37a63067-7174-46fc-8951-d6a2ea1938f3.png)

2022-07-01 19:36 UTC, 0xdcarns requested changes

2022-07-01 19:36 UTC, 0xdcarns commented on src/i18n/resources/en.ts
> +    isdnson: 'he node will setup DNS entries for its peers locally',
missing a "T"

2022-07-01 19:36 UTC, 0xdcarns commented on src/i18n/resources/en.ts
> +      'he hardware mac address of the machine. Used to be used as the unique ID, but is being depreciated',
missing a "T"

2022-07-01 19:36 UTC, 0xdcarns commented on src/i18n/resources/en.ts
> +      'he hardware mac address of the machine. Used to be used as the unique ID, but is being depreciated',
Also "Deprecated" not depreciated..

2022-07-01 19:36 UTC, 0xdcarns commented on src/route/nodes/netid/nodeEdit/NodeEdit.tsx
> +        <Tooltip title={String(t('helper.defaultlistenport'))} placement="top">
the tooltips should go around the NmFormInputTexts components.. if the fields are disabled, put a <span></span> around the input text first..

2022-07-01 19:59 UTC, FatherWolf commented on src/route/nodes/netid/nodeEdit/NodeEdit.tsx
> +        <Tooltip title={String(t('helper.defaultlistenport'))} placement="top">
done

2022-07-01 20:21 UTC, 0xdcarns requested changes

2022-07-01 20:21 UTC, 0xdcarns commented on src/route/nodes/netid/nodeEdit/NodeEdit.tsx
>          <Tooltip title={String(t('helper.dynamicport'))} placement="top">
you can put this as the alternative to the !network?.defaultudpholepunch, then there won't be 2 tooltips..

2022-07-01 20:50 UTC, 0xdcarns requested changes

2022-07-01 20:50 UTC, 0xdcarns commented on src/route/nodes/netid/nodeEdit/NodeEdit.tsx
> +        <Tooltip title={String(t('helper.nodeexpires'))} placement="top">
Any reason why this one is around the Grid item?

2022-07-05 16:53 UTC, 0xdcarns approved these changes

2022-07-05 16:53 UTC, merged